### ISSUE TITLE
64-bit exponent doesn't update properly

### ISSUE THREAD

**Issue by bartgrantham** [evanw/float-toy#3]
If you set the 64-bit exponent to all zeros and toggle the least significant (rightmost) bit it doesn’t update the exponent shown below.  This is on Firefox 72.0.1.

**Comment by bartgrantham** [comment]
This bug appears to exist in the 32-bit exponent as well.

**Comment by thp** [comment]
Also happens with Safari 13.0.4:

![Screenshot 2020-01-24 at 14 23 00](https://user-images.githubusercontent.com/135241/73072352-30fb4e00-3eb5-11ea-92af-317d550cf453.png)

![Screenshot 2020-01-24 at 14 22 56](https://user-images.githubusercontent.com/135241/73072354-30fb4e00-3eb5-11ea-9e56-f41785010846.png)

**Comment by evanw** [comment]
I believe this is not a bug. What you're seeing is the boundary between normal numbers and [denormal numbers](https://en.wikipedia.org/wiki/Denormal_number). From Wikipedia:

> In a normal floating-point value, there are no leading zeros in the [significand](https://en.wikipedia.org/wiki/Significand); instead leading zeros are removed by adjusting the exponent. So 0.0123 would be written as 1.23 × 10<sup>−2</sup>. Denormal numbers are numbers where this representation would result in an exponent that is below the smallest representable exponent (the exponent usually having a limited range). Such numbers are represented using leading zeros in the significand.
>
> The [significand](https://en.wikipedia.org/wiki/Significand) (or mantissa) of an [IEEE floating-point](https://en.wikipedia.org/wiki/IEEE_floating-point) number is the part of a floating-point number that represents the significant digits. For a positive normalised number it can be represented as _m_<sub>0</sub>._m_<sub>1</sub>_m_<sub>2</sub>_m_<sub>3</sub>..._m_<sub>p−2</sub>_m_<sub>p−1</sub> (where _m_ represents a significant digit, and _p_ is the precision) with non-zero _m_<sub>0</sub>. Notice that for a binary [radix](https://en.wikipedia.org/wiki/Radix), the leading binary digit is always 1. In a **denormal number**, since the exponent is the least that it can be, zero is the leading significand digit (0._m_<sub>1</sub>_m_<sub>2</sub>_m_<sub>3</sub>..._m_<sub>p−2</sub>_m_<sub>p−1</sub>), allowing the representation of numbers closer to zero than the smallest normal number. A floating-point number may be recognized as denormal whenever its exponent is the least value possible.
>
> ...
>
> In [IEEE 754-2008](https://en.wikipedia.org/wiki/IEEE_754-2008), denormal numbers are renamed _subnormal numbers_ and are supported in both binary and decimal formats. In binary interchange formats, subnormal numbers are encoded with a [biased exponent](https://en.wikipedia.org/wiki/Exponent_bias) of 0, but are interpreted with the value of the smallest allowed exponent, which is one greater (i.e., as if it were encoded as a 1). In decimal interchange formats they require no special encoding because the format supports unnormalized numbers directly. 

So basically when the exponent reaches 0, floating-point values switch into a special mode called a "denormal number" where the exponent is treated as if it's still 1 but where 1 is no longer added to the mantissa/significand:

<img width="605" src="https://user-images.githubusercontent.com/406394/73125176-b84dcd80-3f58-11ea-97e7-905e4e4a2102.png">

**Comment by bartgrantham** [comment]
Very interesting.  In that case, should I open a feature request for the UI to draw attention to the this weird corner case of IEEE floats and how the format actually changes?  I feel like I learned more from the resolution of this issue than I did playing with the toy. :)
