### ISSUE TITLE
Weird visual update o.?

### ISSUE THREAD

**Issue by uprego** [evanw/float-toy#7]
M gonna boot the tool:
<img width="655" alt="Screenshot 2020-01-25 at 22 59 21" src="https://user-images.githubusercontent.com/10517039/73127815-7d827e80-3fc6-11ea-8e51-6c5c5e6cf501.png">
<hr />
M gonna set bits 32 to 24, in that order, to one.
<img width="676" alt="Screenshot 2020-01-25 at 22 59 29" src="https://user-images.githubusercontent.com/10517039/73127818-81160580-3fc6-11ea-8a79-434787468d81.png">
<hr />
M gonna set bits 32 and 31, in that order, to zero.
<img width="674" alt="Screenshot 2020-01-25 at 22 59 34" src="https://user-images.githubusercontent.com/10517039/73127819-83785f80-3fc6-11ea-8ea7-5732d7f102e2.png">
<hr />
M gonna set bit 30 to zero.

[BOOM](http://www.youtube.com/watch?v=tSJSVmfaMCs)
<img width="674" alt="Screenshot 2020-01-25 at 22 59 38" src="https://user-images.githubusercontent.com/10517039/73127820-87a47d00-3fc6-11ea-9cd5-71056bd2efcc.png">

**Comment by evanw** [comment]
Wow that's super weird. Thanks for reporting it. I can only get it to happen in Chrome. Looks like it's easy to fix.

**Comment by uprego** [comment]
🙇
